"""update table master

Revision ID: 27b6352f39ad
Revises: fb89a79218b9
Create Date: 2023-06-14 15:52:27.497778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b6352f39ad'
down_revision = 'fb89a79218b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_dataset', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_column('nama_dataset')

    # ### end Alembic commands ###
