"""membuat tabel hasil_prediksi

Revision ID: 4aecded09c2f
Revises: bbc9e2e4108d
Create Date: 2023-06-05 14:42:55.872629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aecded09c2f'
down_revision = 'bbc9e2e4108d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_prediksi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('prediksi_donasi', sa.BigInteger(), nullable=False),
    sa.Column('ekspektasi_donasi', sa.BigInteger(), nullable=False),
    sa.Column('mape', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_prediksi')
    # ### end Alembic commands ###
