"""upgrade hasil_prediksi table

Revision ID: 85eaa9d911ed
Revises: 27b6352f39ad
Create Date: 2023-06-15 00:35:31.217508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85eaa9d911ed'
down_revision = '27b6352f39ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_prediksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_master', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'master', ['id_master'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_prediksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_master')

    # ### end Alembic commands ###
